# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="auctex-cont-latexmk"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="run latexmk continuously, report errors via Flymake"

HOMEPAGE="https://github.com/ultronozm/auctex-cont-latexmk.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/auctex"
RDEPEND="app-emacs/auctex"
