# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="doc-view-follow"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Synchronize windows showing the same document"

HOMEPAGE="https://github.com/ultronozm/doc-view-follow.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
