# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="iso-date"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Utilities for working with ISO dates"

HOMEPAGE="https://github.com/lmq-10/iso-date"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
