# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="activities"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Suspend/resume sets of windows, frames, and buffers"

HOMEPAGE="https://elpa.gnu.org/packages/activities.html"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/persist"
RDEPEND="app-emacs/persist"
