# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="activities"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Save/restore sets of windows, tabs/frames, and their buffers"

HOMEPAGE="https://github.com/alphapapa/activities.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/persist"
RDEPEND="app-emacs/persist"
