# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="phpinspect"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="PHP parsing and code intelligence package"

HOMEPAGE="https://github.com/hugot/phpinspect.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/compat"
RDEPEND="app-emacs/compat"
