# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="realgud-ipdb"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="realgud front-end to ipdb"

HOMEPAGE="http://github.com/rocky/realgud-ipdb"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/realgud"
RDEPEND="app-emacs/realgud"
