# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="autorevert-tail-truncate"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="auto-revert-tail your files with RAM control"

HOMEPAGE="https://github.com/shipmints/autorevert-tail-truncate.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
