# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="tex-item"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Commands for working with tex items"

HOMEPAGE="https://github.com/ultronozm/tex-item.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
