# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="tex-parens"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="Like lisp.el, but for tex"

HOMEPAGE="https://github.com/ultronozm/tex-parens.el"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND=""
