# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REPO_URI="https://elpa.gnu.org/packages/"
SOURCE_TYPE="tar"
REALNAME="vecdb"
DIGEST_SOURCES="yes"

inherit g-sorcery gs-elpa

DESCRIPTION="An interface to vector databases for embeddings"

HOMEPAGE="https://github.com/ahyatt/vecdb"
SRC_URI="${REPO_URI}${REALNAME}-${PV}.${SUFFIX}"

SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-emacs/plz
	app-emacs/pg"
RDEPEND="app-emacs/plz
	app-emacs/pg"
